### ISSUE TITLE
Download with watermark missing video ID from name

### ISSUE THREAD

**Issue by unchartedpopsicle** [pablouser1/ProxiTok#86] opened 2022-10-22 19:00 UTC
**Edited as latest version downloads a functional video.**

On an instance running frontend 2.4.2.0 and scraper 2.2.1.1 (for example proxitok.privacydev.net) it works fine, but on the latest version it downloads a ~broken 61 byte~ video file named "tiktok-video--[username].mp4", rather than "tiktok-video-[video ID]-[username].mp4",This seems consistent on all instances and videos. 

**To Reproduce**
1. Go to any video
2. Click on download with watermark

**Comment by NoPlagiarism** [comment] 2022-10-23 12:51
Duplicate of #76

**Comment by NoPlagiarism** [comment] 2022-10-23 13:59
But, yeah
TTDown don't works now too

**Comment by unchartedpopsicle** [comment] 2022-10-23 16:12
> Duplicate of #76

You sure? This is the other download option, and only on the latest version.

**Comment by NoPlagiarism** [comment] 2022-10-23 17:05
Yep, sorry, was wrong

**Comment by pablouser1** [comment] 2022-10-24 18:58
Hi @unchartedpopsicle, thanks for pointing out the issue. It has now been fixed with 23583ef7abfc7c4ade29891f3a6ef073b58e3cdb

The old implementation extracted the ID from the URL passed, which was assumed to use the "https://www.tiktok.com/@USERNAME/video/VIDEO_ID" structure, which was not always true. That's why sometimes the ID was empty.

**Closed** 2022-10-28 14:53 UTC
Labels: bug
