### ISSUE TITLE
User posts are not retreived anymore

### ISSUE THREAD

**Issue by vdemay** [pablouser1/ProxiTok#60] opened 2022-07-18 13:45 UTC
Getting posts from user fails: e,g, https://proxitok.herokuapp.com/@willsmith
I suppose something change on tiktok side

**Comment by pablouser1** [comment] 2022-07-23 16:33
Hi, indeed something changed on their servers, I'm investigating it now. Maybe it has to do with the X-Bogus and msToken GET params? I'm working on a way to generate those tokens.

**Comment by eUgEntOptIc44** [comment] 2022-08-02 22:24
@pablouser1 would be very grateful for a short update on this as I still experience the error mentioned in #61.

**Comment by pablouser1** [comment] 2022-08-04 12:47
> would be very grateful for a short update on this

The "main" fix being discussed right now is in https://github.com/davidteather/TikTok-Api/issues/906#issuecomment-1194750614 but it involves logging into a TikTok account, which (at least in my opinion) defeats the purpose of using an alternative frontend.

As I said before, I ended up generating X-Bogus and msToken tokens but even with those I'm still getting captcha issues. Maybe they are not valid?

**Comment by pablouser1** [comment] 2022-08-11 22:09
This issue has been fixed :tada:

Thanks to @H1W0XXX we can now generate valid X-Bogus tokens.

This, indirectly, fixes #39 and breaks Discover.

For instance hosters: Make sure to use the latest version of ProxiTok and SignTok. For now, only SignTok supports X-Bogus, but eventally other signers will support it.

**Comment by desbest** [comment] 2022-08-12 18:15
> This issue has been fixed 🎉
> 
> For instance hosters: Make sure to use the latest version of ProxiTok and SignTok. For now, only SignTok supports X-Bogus, but eventally other signers will support it.

If the issue is fixed, when will the official `proxitok.herokuapp.com` instance be updated to the latest version, to reflect the changes?

**Comment by NoPlagiarism** [comment] 2022-08-12 22:12
@desbest Instance updated
[Check url mentioned earlier](https://proxitok.herokuapp.com/@willsmith)

**Comment by desbest** [comment] 2022-08-12 22:20
Why does this profile not work?
[Check this URL for details.](https://proxitok.herokuapp.com/@avamax)

> There was an error processing your request!
> HTTP Code: 200
> API error code -1 (UNKNOWN_ERROR)

**Comment by NoPlagiarism** [comment] 2022-08-12 23:13
or is it?
Checked 5 minutes ago
![png](https://i.vgy.me/eeGWTt.png "Checked 5 mins ago")

**Comment by pablouser1** [comment] 2022-08-13 11:46
I'm currently not having issues on the official instance. I'll leave this issue opened for some time in case something happens.

**Comment by NoPlagiarism** [comment] 2022-08-17 12:14
@pablouser1 Happened
Problem on ProxiTok 2.4.0.0 or Scraper 2.2.0.0
https://cringe.whatever.social is working

**Comment by pablouser1** [comment] 2022-08-17 12:57
> @pablouser1 Happened Problem on ProxiTok 2.4.0.0 or Scraper 2.2.0.0 https://cringe.whatever.social is working

https://github.com/pablouser1/ProxiTok/issues/72#issuecomment-1217969598

**Comment by FillingTheVoidOnYT** [comment] 2022-08-19 17:14
when using the mobile browser duckduckgo no user posts want to load

**Comment by NoPlagiarism** [comment] 2022-08-19 18:06
> the mobile browser duckduckgo no user pos
instance. Name the instance url

**Comment by FillingTheVoidOnYT** [comment] 2022-08-19 18:08
> the mobile browser duckduckgo no user pos
> instance. Name the instance url

It’s the official instance

**Comment by pablouser1** [comment] 2022-09-09 20:40
It looks like it is now stable... I'll close this issue for now

**Closed by pablouser1** 2022-09-09 20:40 UTC
