### ISSUE TITLE
Add a login portal to secure proxitok access

### ISSUE THREAD

**Issue by pawisoon** [pablouser1/ProxiTok#171] opened 2023-08-24 10:52 UTC
As a self-hosting user, I would like proxitok to have the option to secure it behind a login portal.

**Comment by NoPlagiarism** [comment] 2023-08-25 05:16
Duplicate of #121 

You can secure it at server-level: [Apache](https://www.cyberciti.biz/faq/howto-setup-apache-password-protect-directory-with-htaccess-file/)/[Nginx](https://www.cyberciti.biz/faq/nginx-password-protect-directory-with-nginx-htpasswd-authentication/)

**Closed** 2023-09-28 18:03 UTC
Labels: enhancement
