### ISSUE TITLE
self-hosted instance same API error code -1 (UNKNOWN_ERROR)

### ISSUE THREAD

**Issue by bugbounted2022** [pablouser1/ProxiTok#61] opened 2022-07-21 03:18 UTC
Hi [pablouser1](https://github.com/pablouser1),
I'm clone proxitok latest commit [d0057e7](https://github.com/pablouser1/ProxiTok/commit/d0057e77e37953562c69cd8716d4755bcda13374) to my own ubuntu 22 server & runnig with docker compose . but after visit default port (8080) & search public tiktok user give error below :

There was an error processing your request!

HTTP Code: 200

API error code -1 (UNKNOWN_ERROR)

**Comment by gabor-ig** [comment] 2022-07-23 12:19
I can confirm. Issue remains the same also after cycling through multiple IP addresses by connecting through a VPN

**Comment by pablouser1** [comment] 2022-07-23 16:33
Duplicate of #60, We'll continue the debate there

**Closed by pablouser1** 2022-07-23 16:33 UTC
